#+BLOG: perspicaz
#+POSTID: 655
#+DATE: [2021-08-09 Mon 15:50]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil ^:{}
#+PARENT:
#+CATEGORY: Uncategorized
#+TAGS:
#+DESCRIPTION:
#+TITLE: Criando arquivos com nomes sequenciais usando letras ao invés de números
#+PERMALINK: criando-arquivos-com-nomes-sequenciais-usando-letras-ao-inves-de-numeros

Criar arquivos sequencias usando números como por exemplo:

: arq-01.txt
: arq-02.txt
: arq-03.txt

são coisas muito simples e muito úteis também. Na dica de hoje vou abordar a mesma tarefa incrementando letras ao invés de números. Pode ser útil em alguns casos, mas com certeza é um ótimo exercício! 😁

#+HTML: <!--more Continue lendo...-->

Para simplificar, vou considerar apenas o intervalo "a-z" e duas posições como no exemplo citado, tornando possível criar até =626= arquivos (26 * 26).

Pretendo abordar duas formas distintas e incrementar letras:

** Abordagem 1
Utilizando a tabela ascii como referência (=man 7 ascii=).
   Onde você pode conferir que os intervalos numéricos são:
     * Binário não consta na página de manual da tabela ascii mas seria o caso fazer uma conversão numérica.
     | Notação     |  Início |     Fim |
     |-------------+---------+---------|
     | Octal       |     141 |     172 |
     | Decimal     |      97 |     122 |
     | Hexadecimal |      61 |      7A |
     | Binário     | 1100001 | 1111010 |

   A implementação neste caso é basicamente escolher a notação mais conveniente na linguagem/ferramenta escolhida e utilizar o método para transformar número em letra.

** Abordagem 2
Criando uma lista com intervalo de "/a"/ a "/z/" e usando a posição delas como referência.
   Exemplo:
   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | ... | 26 |
   |---+---+---+---+---+---+---+---+---+-----+----|
   | a | b | c | d | e | f | g | h | i | ... |  z |

   Ou seja, cada posição da lista corresponde a uma letra.

   Ou seja, criar uma lista e iterar pelo seu índice para obter a letra. Neste exemplo o /array/ é inicializado em 1 mas pode ser o 0 dependendo da linguagem/ferramenta utilizada.

Vamos para às soluções:

** Shell

Obs.: Assumindo apenas soluções mais portáveis entre os vários /shells/ existentes. Testadas no ~ash~ (versão atual mais próxima do ~sh~ original).

*** [[Abordagem 1]]
a) Usando ~bc~ para transformar o intervalo decimal gerado pelo ~seq~ em notação octal e acertando a sintaxe para o ~prinft~ conseguir converter:
  #+BEGIN_SRC sh
    seq=$(seq 97 122)
    for dec1 in $seq; do
        oct1=$(echo 'ibase=A;obase=8;'$dec1|bc)
        oct1="\\"$oct1
        for dec2 in $seq; do
              oct2=$(echo 'ibase=A;obase=8;'$dec2|bc)
              oct2="\\"$oct2
              filename=$(printf 'arq-%b%b.txt\n' "$oct1" "$oct2")
              touch $filename
        done
    done
  #+END_SRC

b) Usando ~awk~ (que poderia ter sido no exemplo "a)" também) para criar os /filenames/. Como ~awk~ não cria arquivos, recorro ao ~shell~ para concluir o serviço:
  #+BEGIN_SRC awk
    awk 'BEGIN {
        for ( i = 97; i <= 122; i++ ) {
            for ( j = 97; j <= 122; j++ ) {
                printf "arq-%c%c.txt\n", i, j;
            }
        }
    }' | xargs touch
  #+END_SRC

c) Uma forma exótica usando a calculadora ~dc~ (pertence ao pacote padrão da ~bc~):
    #+BEGIN_SRC sh
    seq=$(seq 97 122)
    for dec1 in $seq; do
        l1=$(echo "${dec1}P"|dc)
        for dec2 in $seq; do
            l2=$(echo "${dec2}P"|dc)
            filename="arq-$l1$l2.txt"
            touch $filename
        done
    done
    #+END_SRC

    A mágica aqui é feita pelo parâmetro "~P~" que instrui à ~dc~ converter o número decimal para o seu corresponde ~ascii~ (a documentação não é muito clara sobre essa conversão).
*** [[Abordagem 2]]

a) O ~sh~ padrão não possui estruturas de dados como /array/, então precisamos simular um com /string/:

  #+BEGIN_SRC sh
    chars='abcdefghijklmnopqrstuvwxyz'
    seq=$(seq 1 26)

    for dec1 in $seq; do
        char1=$(echo $chars | cut -c $dec1)
        for dec2 in $seq; do
            char2=$(echo $chars | cut -c $dec2)
            filename="arq-${char1}${char2}.txt"
            touch $filename
        done
    done
  #+END_SRC

b) Para usar /arrays/ num /shell/ padrão precisamos recorrer a, por exemplo, ~awk~:

  #+BEGIN_SRC awk
    awk 'BEGIN {
        n=split("abcdefghijklmnopqrstuvwxyz", chars, //);
        for ( i = 1; i <= n; i++ ) {
            for ( j = 1; j <= n; j++ ) {
                printf "arq-%s%s.txt\n", chars[i], chars[j];
            }
        }
    }' | xargs touch
  #+END_SRC

c) Usando o ~sed~ para criar uma lista de letras:
   #+BEGIN_SRC sh
     chars='abcdefghijklmnopqrstuvwxyz'
     for c1 in $(echo $chars | sed 's/\B/ /g'); do
         for c2 in $(echo $chars | sed 's/\B/ /g'); do
             filename="arq-${c1}${c2}.txt"
             echo touch $filename
         done
     done
   #+END_SRC

** Perl

Obs: Existem bibliotecas externas que simplificam a solução para apenas uma linha não serão usadas nesse exercício.

*** [[Abordagem 1]]

a) Criando os /loops/ e usando a função ~chr~ para converter número para letra:

   #+BEGIN_SRC perl
     for ( my $i = 97; $i <= 122; $i++ ) {
         my $char1 = chr $i;
         for ( my $j = 97; $j <= 122; $j++ ) {
             my $char2 = chr $j;
             my $filename = 'arq-' . $char1 . $char2 . '.txt';
             open my $fh, '>', $filename;
         }
     }
   #+END_SRC

b) Utilizando o comando ~pack~ e um estildo diferente de /loop/ em relação ao exercício "a)":

   #+BEGIN_SRC perl
     my @range = 97 .. 122;
     for my $i ( @range ) {
         my $char1 = pack 'C', $i;
         for my $j ( @range )  {
             my $char2 = pack 'C', $j;
             my $filename = "arq-${char1}${char2}.txt";
             IO::File->new($filename,'w');
         }
     }
   #+END_SRC

c) Utilizando o comando ~sprintf~ e permutação com o ~glob~:

   #+BEGIN_SRC perl
     use File::Copy qw[cp];
     my @range = 97 .. 122;
     my @permute = glob sprintf '{%s}{x}{%s}', map {join ',', @range} 1..2;
     foreach my $permute ( @permute ) {
         my @char = split /x/, $permute;
         my $filename = sprintf 'arq-%c%c.txt', @char;
         cp '/dev/null', $filename;
     }
   #+END_SRC

*** [[Abordagem 2]]
a)
   #+BEGIN_SRC
    
