#+BLOG: perspicaz
#+POSTID: 282
#+DATE: [2016-11-24 Thu 20:01]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+PARENT:
#+CATEGORY: DrCapiroto
#+TAGS:
#+DESCRIPTION:
#+TITLE: [DrCapirotoExplica] Amor e desejo seriam a mesma coisa?
#+PERMALINK: drcapirotoexplica_-_amor_e_desejo_seriam_a_mesma_coisa

Saudações leitores(as)!

Alguns acontecimentos cotidianos despertaram minha curiosidade no assunto proposto e finalmente consegui reunir elementos fortes o suficiente para invocar o DrCapiroto (troca equivalente?) para mais uma entrevista, o cara estava sobrecarregado de trabalho e a densidade da "realidade" acabava por sobrepujar a capacidade de comunicação... Bem, deixemos os detalhes técnicos para lá, rsrss. Mas então, novamente conversei de forma coloquial (ou quase) para simplificar a compreensão e mais uma vez saí com mais dúvidas do que certezas... Pensei até que o assunto pudesse esquentar mas o DrCapiroto trata da questão com extrema frieza. Vejamos os detalhes na transcrição da entrevista.
#+HTML: <!--more Continue lendo...-->

#+HTML: <hr>
Ronaldo: Saudações DrCapiroto! Notei que esteve sobrecarregado ultimamente. Trabalhando bastante?
DrCapiroto: Amaldiçoadamente.
Ronaldo: Pois bem, o invoquei desta vez para discutirmos um assunto que costuma arrancar suspiros e produzir sonhos em pessoas de todas as idades e...
DrCapiroto: O destino do sonhador é acordar.
Ronaldo: ... é... bem... o assunto hoje é sobre o amor e sua ligação com o desejo. Existiria de fato uma ligação intrínseca entre os dois? Ou até mesmo seriam exatamente a mesma coisa?
DrCapiroto: Sem definir o que é "amor" e o que é "desejo" no contexto desta conversa não é possível estabelecer uma ligação ou mesmo determinar suas divergências. Se por "amor" é assumido o "amor romântico" muito explorado comercialmente em poesias, filmes, propagandas etc, eu respondería-lhe "Sim, o amor e o desejo são uma única coisa", inclusive é a abordagem que desperta interesse nas criaturas humanas por lhes aguçar o "desejo", mais precisamente por lhe provocar inveja. Entretanto, este conceito de amor é caótico e incompleto sob vários aspectos e remete à interpretação de que existem várias formas de amor, uma vez que este conceito por si só não é capaz de explicar o sentimento de uma mãe pelo seu filho, ou como explicar o ciúme e os crimes passionais, para citar alguns exemplos. O resultado desta forma pensamento é absorvido pelo senso comum que, por sua vez, alimenta a forma pensamento formando um ecossistema, explorável pelos três poderes. Como resultado, temos uma gigantesca quantidade de fórmulas, classificações e teorias a respeito.
Ronaldo: O ciume não é uma forma de amor?
DrCapiroto: A resposta é conveniente a quem responde. Se o ciumento questiona-se ou é questionado, a resposta é "sim, ciúme é uma forma de amor". No caso da parte prejudicada seria "não", até porque, qualquer outra resposta daria margem à interpretação de que amor pode ser algo negativo. Uma característica comportamental do ciumento é a constante necessidade de justificar suas ações, seja para si próprio, seja socialmente. Minha resposta é não, não há amor no cíume.
Ronaldo: Ciúmes e crimes passionais foram algumas das razões para resolver indagar sobre este assunto. Sobre crimes passionais, teria algo a mencionar?
DrCapiroto: Crimes passionais são o extremo da expressão do ciúme, autoafirmação da posse pelo outro ou ainda dos medos da solidão, perda entre várias outras combinações de sentimentos, uma criatura humana comum é confusa consigo própria sozinha e quando se alia a outra multiplica suas confusões com as do companheiro. Não há amor em nenhum desses pensamentos e/ou atitudes.
Ronaldo: Nos casos de traição é mais comum vermos respostas violentas praticadas por homens, haveria alguma razão esta tendência?
DrCapiroto: A traição afeta o senso de masculinidade, em outras palavras, "perfura" profundamente o orgulho do macho e a reação costuma ser violenta. As mulheres costumam suportar melhor essas coisas.
Ronaldo: O senhor falou agora a pouco que ciúme não é amor, mas não é possível imaginar a ausência de ciumes num relacionamento, alguma pista do porquê?
DrCapiroto: Sejamos práticos, num relacionamento qualquer, como um casamento hetero por exemplo, a mulher dirigi-se ao homem como "meu esposo" e o homem dirigi-se à mulher como "minha esposa", já é determinado uma relação de posse simplemente pelo uso dos pronomes possessivos, essa relação de posse não é amor, é uma convenção comum para garantir e proteger a união/relação. Em certas ocasiões afirma a obrigação de um para com o outro. O ciúme é negativo quando traz prejuízo para um ou ambos.
Ronaldo: O amor de uma mãe para com seu filho seria uma forma especial de amor?
DrCapiroto: Podemos dizer que sim. É a manifestação do amor real, a fraternidade. O mesmo amor praticado por irmãos e amigos. O que variam são as afinidades, é esperado que uma mãe tenha muitas e profundas afinidades com seu filho.
Ronaldo: Qual seria a configuração de amor versus desejo no caso mencionado do casal hetero?
DrCapiroto: A presença do desejo não implica na ausência do amor. É natural dois adultos saudáveis manifestarem desejo um pelo outro, pois esta é umas das condições do "animal". Sobrepujar o "animal" é condição evolutiva.
Ronaldo: Conheço várias pessoas que buscam desesperadamente o "amor romântico" dos filmes e das poesias, alguns casam-se inúmeras vezes, outras enfrentam grande angústia e frustração, entretanto não desistem porque acreditam que ter sucesso na busca é recompensador. Seria de fato esta a motivação para isto?
DrCapiroto: É a pura manifestação do desejo através da inveja. O amargo da ausência é equilibrada pelo queimar das chamas da paixão, cuja natureza é invariavelmente destrutiva (fogo). O amor real é monótono demais para preencher este vazio, esta necessidade eufórica. A fé é usada de forma negativa para perpetuar o ciclo. Nalguns casos, esta paixão figura-se como um entorpecente, não sendo diferente do comportamento manifestado por dependentes químicos... Este estado de fragilidade é facilmente explorável e portanto, perigoso.
Ronaldo: Explorável!?
DrCapiroto: O amor, no conceito do senso comum, é algo facilmente manipulável. Criá-lo, administrá-lo e destruí-lo é uma das ferramentas disponíveis aos três poderes. O fluxo segue a conveniência e as modas mudam para atender grandes interesses.
Ronaldo: Acho que vamos encerrar por aqui pois agora fiquei perturbado...
DrCapiroto: Que seja.
#+HTML: <hr>

Espero conseguir dormir hoje... Até o próximo "DrCapirotoExplica"!

#  LocalWords:  toc pri DrCapiroto DrCapirotoExplica PERMALINK rsrss
#  LocalWords:  drcapirotoexplica respondería-lhe
